### ISSUE TITLE
Tango Monitor problems on server startup

### ISSUE THREAD

**Issue by reszelaz** [tango-controls-migration-tests/TangoTickets#12]
Hi,

I would like to consult the following behavior that I’ve observed during the device server startup process. I use Python language to develop the server. I decorate the init_device method of a Tango class so that when it returns it launches a thread that will push a change event of this device attributes.
Due to the race condition, from time to time, the server fails to start and reports problems with acquiring the serialization monitor. I paste below the server logs with “-v6” option.

```
[...]
18000179 [140255238956800] DEBUG dserver/MacroServer/demo1 Adding logging target console::cout to door/demo1/1
1518000179 [140255238956800] DEBUG dserver/MacroServer/demo1 Leaving Logging::add_logging_target (internal impl)
1518000179 [140255238956800] DEBUG dserver/MacroServer/demo1 Leaving DeviceImpl::init_logger
1518000179 [140255238956800] DEBUG dserver/MacroServer/demo1 Leaving get_device_attribute_property
1518000179 [140255238956800] DEBUG dserver/MacroServer/demo1 Leaving get_device_attribute_property
1518000179 [140254480680704] DEBUG dserver/MacroServer/demo1 In get_monitor() Door/demo1/1, thread = 9, ctr = 0
1518000179 [140255238956800] DEBUG dserver/MacroServer/demo1 DeviceClass::export_device() arrived
1518000179 [140255238956800] DEBUG dserver/MacroServer/demo1 In get_monitor() Door/demo1/1, thread = 0, ctr = 1
1518000179 [140255238956800] DEBUG dserver/MacroServer/demo1 Thread 0: waiting !!
1518000181 [140253374666496] DEBUG dserver/MacroServer/demo1 In get_monitor() tango://pc255.cells.es:10000/dserver/pool/demo1, thread = 8, ctr = 0
1518000181 [140253374666496] DEBUG dserver/MacroServer/demo1 In rel_monitor() tango://pc255.cells.es:10000/dserver/pool/demo1, ctr = 1, thread = 8
1518000181 [140253374666496] DEBUG dserver/MacroServer/demo1 Signalling !
1518000181 [140253374666496] DEBUG dserver/MacroServer/demo1 In get_monitor() tango://pc255.cells.es:10000/dserver/pool/demo1, thread = 8, ctr = 0
1518000181 [140253374666496] DEBUG dserver/MacroServer/demo1 In rel_monitor() tango://pc255.cells.es:10000/dserver/pool/demo1, ctr = 1, thread = 8
1518000181 [140253374666496] DEBUG dserver/MacroServer/demo1 Signalling !
1518000182 [140255238956800] DEBUG dserver/MacroServer/demo1 TIME OUT for thread 0
1518000182 [140255238956800] DEBUG dserver/MacroServer/demo1 Entering DeviceClass destructor for class Door
1518000182 [140255238956800] DEBUG dserver/MacroServer/demo1 Entering DeviceClas::delete_dev method for device with index 0
1518000182 [140255238956800] DEBUG dserver/MacroServer/demo1 Leaving DeviceClass delete_dev
1518000182 [140254480680704] DEBUG dserver/MacroServer/demo1 Attribute::fire_change_event() entering ...
1518000182 [140255238956800] DEBUG dserver/MacroServer/demo1 Leaving DeviceClass destructor for class Door
1518000182 [140254480680704] DEBUG dserver/MacroServer/demo1 In rel_monitor() Door/demo1/1, ctr = 1, thread = 9
1518000182 [140254480680704] DEBUG dserver/MacroServer/demo1 Signalling !
_set_attribute_push: leaving
1518000182 [140255238956800] DEBUG dserver/MacroServer/demo1 Entering DeviceImpl destructor for device dserver/MacroServer/demo1
1518000182 [140255238956800] DEBUG dserver/MacroServer/demo1 Leaving DeviceImpl destructor for device dserver/MacroServer/demo1
1518000182 [140255238956800] DEBUG dserver/MacroServer/demo1 Entering DeviceClass destructor for class DServer
1518000182 [140255238956800] DEBUG dserver/MacroServer/demo1 Leaving DeviceClass destructor for class DServer
MainThread     INFO     2018-02-07 11:43:02,871 TaurusRootLogger: Exiting
MainThread     CRITICAL 2018-02-07 11:43:02,871 TaurusRootLogger: Server exited with DevFailed
Traceback (most recent call last):
 File "/home/zreszela/workspace/sardana/src/sardana/tango/core/util.py", line 992, in run_tango_server
   util.server_init()
DevFailed: DevFailed[
DevError[
   desc = Not able to acquire serialization (dev, class or process) monitor
 origin = TangoMonitor::get_monitor
 reason = API_CommandTimedOut
severity = ERR]
]
MainThread     INFO     2018-02-07 11:43:02,871 TaurusRootLogger: Exited
1518000182 [140255238956800] DEBUG dserver/MacroServer/demo1 SubDevDiag::~SubDevDiag() entering ...  
terminate called after throwing an instance of 'omni_thread_fatal'
Aborted
```

And here my conclusions. I imagine that thread 9 is the one that tries to push the change event. It acquires the monitor, but due to an unknown reason is not able to push the event and release the monitor. Then there are two more threads. Thread 0 looks to me like the one that is doing the job of exporting the device and it waits for the monitor and timeouts making the server to fail. I have no idea what thread 8 is doing.

For the moment I just observed it with the Sardana server, if you think it is worth, I could work on reproducing it in a simplified scenario.

Thanks in advance for taking your time to look into this issue!

**Comment by bourtemb** [comment]
Hi,
I think it would be interesting to reproduce it in a simplified scenario indeed.
Cheers,
Reynald

**Comment by reszelaz** [comment]
A attch the [PyDsExp.txt](https://github.com/tango-controls/TangoTickets/files/1703888/PyDsExp.txt) (please change the extension to py before running it).

It has one attribute *attr1*. I start the thread in the `init_device` so I was able to eliminate the decorator. This thread will push the change event of this attribute. With this server it almost always fail, maybe 5% of times it avoids the deadlock and the monitor timeout. I also paste the log messages executed with the "-v6" option. 

```
[...]
1518020014 [139741420840704] DEBUG dserver/PyDsExp/zreszela Leaving DeviceImpl::init_logger
1518020014 [139741420840704] DEBUG dserver/PyDsExp/zreszela Leaving get_device_attribute_property
1518020014 [139741420840704] DEBUG dserver/PyDsExp/zreszela Leaving get_device_attribute_property
1518020014 [139741420840704] INFO test/pydsexp/1 In PyDsExp.__init__
1518020014 [139741420840704] DEBUG test/pydsexp/1 -> PyDsExp.init_device()
1518020014 [139741420840704] INFO test/pydsexp/1 In Python init_device method
1518020014 [139740988831488] DEBUG dserver/PyDsExp/zreszela In get_monitor() test/pydsexp/1, thread = 6, ctr = 0
1518020014 [139741420840704] DEBUG test/pydsexp/1 <- PyDsExp.init_device()
1518020014 [139741420840704] DEBUG dserver/PyDsExp/zreszela DeviceClass::export_device() arrived
1518020014 [139741420840704] DEBUG dserver/PyDsExp/zreszela In get_monitor() test/pydsexp/1, thread = 0, ctr = 1
1518020014 [139741420840704] DEBUG dserver/PyDsExp/zreszela Thread 0: waiting !!
1518020017 [139741420840704] DEBUG dserver/PyDsExp/zreszela TIME OUT for thread 0
1518020017 [139741420840704] DEBUG dserver/PyDsExp/zreszela Entering DeviceClass destructor for class PyDsExp
1518020017 [139741420840704] DEBUG dserver/PyDsExp/zreszela Entering DeviceClas::delete_dev method for device with index 0
1518020017 [139741420840704] DEBUG dserver/PyDsExp/zreszela Leaving DeviceClass delete_dev
1518020017 [139741420840704] DEBUG dserver/PyDsExp/zreszela Leaving DeviceClass destructor for class PyDsExp
1518020017 [139740988831488] DEBUG dserver/PyDsExp/zreszela Attribute::fire_change_event() entering ...
1518020017 [139740988831488] DEBUG dserver/PyDsExp/zreszela In rel_monitor() test/pydsexp/1, ctr = 1, thread = 6
1518020017 [139740988831488] DEBUG dserver/PyDsExp/zreszela Signalling !
1518020017 [139741420840704] DEBUG dserver/PyDsExp/zreszela Entering DeviceImpl destructor for device dserver/PyDsExp/zreszela
1518020017 [139741420840704] DEBUG dserver/PyDsExp/zreszela Leaving DeviceImpl destructor for device dserver/PyDsExp/zreszela
1518020017 [139741420840704] DEBUG dserver/PyDsExp/zreszela Entering DeviceClass destructor for class DServer
1518020017 [139741420840704] DEBUG dserver/PyDsExp/zreszela Leaving DeviceClass destructor for class DServer
Traceback (most recent call last):
  File "workspace/test_python/PyDsExp.py", line 55, in <module>
    U.server_init()
PyTango.DevFailed: DevFailed[
DevError[
    desc = Not able to acquire serialization (dev, class or process) monitor
  origin = TangoMonitor::get_monitor
  reason = API_CommandTimedOut
severity = ERR]
]
1518020017 [139741420840704] DEBUG dserver/PyDsExp/zreszela SubDevDiag::~SubDevDiag() entering ... 
terminate called after throwing an instance of 'omni_thread_fatal'
Aborted
```

**Comment by reszelaz** [comment]
I think that this problem does not happen with Tango7. At least I was not able to reproduce it in approx 20 times I tried to start the server. With Tango 9 it fails almost always.
